api/urls.py
from django.urls import path,include
from rest_framework import routers

from .views import UserViewSet


router=routers.DefaultRouter()

router.register('user/',UserViewSet)

urlpatterns=[
    path('',include(router.urls)),
   
]

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings



# app_name='home'

# urlpatterns = [

#     path('',views.index,name='index'),
# ]
# if settings.DEBUG: 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import delete_user, edit_user, register_user, user_list, user_profile

app_name="user"

urlpatterns=[
    path('register_user/',register_user,name='register_user'),
    path('user_list/',user_list,name='user_list'),
    path('edit_user/<int:id>',edit_user,name='edit_user'),
    path('user_profile/<int:id>',user_profile,name='user_profile'),
    path('delete_user/<int:id>',delete_user,name='delete_user'),
    
]

usermanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    # path('',include('home.urls')),
    path('api/',include('api.urls')),




]
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

GENDER=(
    ("MALE","MALE"),
    ("FEMALE","FEMALE"),
    ("NON-BINARY","NON-BINARY"),
    ("TRANSGENDER","TRANSGENDER"),

)

class User(models.Model):
    first_name = models.CharField(max_length=12 ,)
    last_name = models.CharField(max_length=20) 
    image = models.ImageField(upload_to='images/')
    gender = models.CharField(max_length=20, choices = GENDER,default = 'FEMALE')
    phone_number = PhoneNumberField
    email =models.EmailField()
    city= models.CharField(max_length=20, default='Nairobi')
    company =models.CharField(max_length=20)
    joining_date =models.DateField(null=True)
    contract=models.FileField(upload_to='documents/%Y/%m/%d')
    resume=models.FileField(upload_to='documents/%Y/%m/%d')
    course_name =models.CharField(max_length=20)
    salary =models.BigIntegerField(null=True)
    
    
    def __str__(self):
        return self.first_name

user/forms.py
from django import forms
from django.forms.widgets import Widget
from .models import User


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields ="__all__"
        widgets = {
        'first_name':forms.TextInput(attrs={'class':'form_control'}),
        'last_name':forms.TextInput(attrs={'class':'form_control'}),
        'image':forms.FileInput(attrs={'class':'form_control'}),
        'gender':forms.Select(attrs={'class':'form_control','id':'gender',}),
        'phone_number':forms.TextInput(attrs={'class':'form_control'}),
        'email':forms.EmailInput(attrs={'class':'form_control'}),
        'city':forms.TextInput(attrs={'class':'form_control'}),
        'company':forms.TextInput(attrs={'class':'form_control'}),
        'joining_date':forms.DateTimeInput(attrs={'class':'form_control'}),
        'contract':forms.FileInput(attrs={'class':'form_control','id':'contract'}),
        'resume':forms.FileInput(attrs={'class':'form_control','id':'resume'}),
        'course_name':forms.TextInput(attrs={'class':'form_control'}),
        'salary':forms.NumberInput(attrs={'class':'form_control'}),
         }  
        labels = {
           
              'image':"Profile Photo",
               'city':"City of Residence",
             
        }

api/views.py
from user.models import User
from django.shortcuts import render
from rest_framework import viewsets

from .serializers import UserSerializer


# Create your views here.



class UserViewSet(viewsets.ModelViewSet):
    queryset =User.objects.all()
    serializer_class=UserSerializer

home/views.py
from django.shortcuts import render
from user.models import User

# Create your views here.
# def index(request):
#     user=User.objects.count()
   
#     data={'user':user}
       
#     return render(request,'index.html',data)

user/views.py
from django.shortcuts import render,redirect
from .forms import UserRegistrationForm
from .models import User
from django.core.paginator import Paginator


def register_user(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('user:user_list')
            
        else:
            print(form.errors)    
    else:
        form = UserRegistrationForm()
    return render(request,'register_user.html',{'form':form})


def edit_user(request,id):
    user=User.objects.get(id=id)
    if request.method=='POST':
        form=UserRegistrationForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
    else:
        form=UserRegistrationForm(instance=user)
        return render(request,'edit_user.html',{'form':form})        
        
def user_profile(request,id):
    user=User.objects.get(id=id)
    return render(request,'user_profile.html',{'user':user})

def delete_user(request,id):
    user=User.objects.get(id=id)
    user.delete()
    return redirect('user:user_list')

def user_list(request):
    user=User.objects.all()

    paginator = Paginator(user, 7) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'user_list.html', {'page_obj': page_obj})

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>Document</title>
    {% load static %}

</head>
<body style="background-color: rgb(212, 207, 207)">
   
    <header style="background-color: white;">
        {% load static %}
       <div > 
            <img class ="pic" style="margin-top: 0.5%;
            width: 260px;
            height: 80px;
            margin-left: 3%;
            margin-bottom: -0.7%;
            " src="https://akirachix.com/img/akirachix-logo.png?_cchid=0c9da6ea6289ffb759cd3b6a36254675"></a>
            <span style="margin-top: 10%; margin-left: 45%;">Register entity:</span>
           <span><a id="reg" href="{% url 'user:register_user' %}">User</a></span>
           
             
        </div>

            <hr style="color: black; height: 4px;">
     </header> 
     <style>
         #reg{
             color: purple;
             font-size: 13px;
             text-decoration: none;
             border: solid 1px rgb(232, 152, 235);
             padding: 10px;
             border-radius: 10px;
             margin-top: 10px;
         }
         #reg:hover{
             background-color:rgb(241, 190, 241) ;
            
         }
         span{
             padding: 10px;
             margin-bottom: -5%;
             color: rgb(46, 3, 46);
          
         
         }
     </style>

    {% block content %}
    {% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    
</body>
</html>

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <title>User Registration</title>
</head>
<body>
  {% extends 'base.html' %}

  {% block content %}
  

  
  <div id="formbody">
  <div id="imgname">
    
    

  <h1 style="margin-left: 15%; font-weight: bold; font-family: 'Montserrat', sans-serif;
  margin-top: -3%;font-size: 45px;color: purple;">
  Welcome to codeHive</h1>
  <img id="courses" src="https://www.alshafak.com/wp-content/uploads/2021/03/32.jpeg">
 
</div>

    <div class="form" style="margin-left: 10%; margin-top: 13%;">
     
   
    
      <h1 style="font-weight: bold; font-family: 'Montserrat', sans-serif;
      margin-top: -3%; font-size: 25px;color: rgb(46, 9, 106);">View Registered Entities:</h1>
      
     <h1><a id="link" href="{% url 'student:student_list' %}"> {{ students }} codeHive Students </a></h1>
     <h1><a id="link" href="{% url 'trainer:trainer_list' %}">{{ trainers }} codeHive Trainers</a></h1>
     <h1><a id="link" href="{% url 'course:course_list' %}">{{ courses }} codeHive Courses</a></h1>
     <h1><a id="link" href="{% url 'events:calendar' %}">{{ events }} codeHive Events</a></h1>
     
  
</div>
</div>
      <style>
     
       

          #link{
           
         padding: 10px;
         background-color: purple;
         color: white;
         height: 40px;
         width: 300px;
         border-radius: 10px; 
         margin-left: 20%;
         margin-top: 10%;
         font-size: 20px;
         font-weight: bold;
         text-decoration: none;
         font-family: 'Montserrat', sans-serif;
       
         
          }
        #courses{
          width: 120%;
          margin-top: -2%;
        
          
        }
        
        #formbody{
         
          display: flex;
          width: 95%;
          background-color: white;
          border-radius:20px ;
          margin-left: 2.5%;
          
       
          
          
        }
        #imgname{
          margin-left: 3%;
          margin-top: 3%;
        }
        
     
         
      </style>
       {% endblock content %}
</body>
</html>

user/templates/edit_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <title>User Registration</title>
</head>
<body style="background-color: rgb(211, 209, 209);">
    <div class="form">
      <img class = "pic" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAriIaiHNiXxhv7x1m99_HC9s55DEELgOHPEobCvdI3OFyx5LGDE0EHUZf3WG5cdvMh6A&usqp=CAU">
    <h1 style="font-size: 40px;color: purple;">User Management</h1>
    <hr>
   
    <form method="POST" enctype="multipart/form-data"  >

      {% extends 'base.html' %}

      {{ form.as_p }}
      {% csrf_token %}
        <button type="submit" 
        style="background-color: purple; 
        color: white;width: 30%;
        height: 40px;
         border-radius: 10px; 
         font-family: 'Montserrat', sans-serif;
         font-size: 20px;
         font-weight: bold;">
         SUBMIT</button>
    </form>
   
     
   
</div>
      <style>
        
        .pic{
          width: 40%;
          margin-bottom: -2%;
        }
        
          body{
        margin:0;
        font-weight: bold;
        font-family: 'Montserrat', sans-serif;
        font-size:15px;
        background:#fcfcfc;
        background-repeat: no-repeat;
          }
          h1{
          font-family: 'Montserrat', sans-serif;
          padding-top: 12px;
          }
          .form{
            margin:4% auto 0 auto;
            padding:30px;
            width:700px;
            height:auto;
            overflow:hidden;
            background:#fcfafb;
            border-radius:20px; 
          }
          .form_control{
           width: 98%;
           outline: none;
           border: 2px solid rgb(99, 51, 99) ;
           font-size: 13px;
           padding: 8px 10px;
           border-radius: 5px;  
           font-family: 'Montserrat', sans-serif;
           font-weight: bold; 
           display: flex;  
       }
       #gender{
         background-color: white;
         width: 102%;
         height: auto;
       }
     
      </style>
      
</body>
</html>

user/templates/register_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <title>User Registration</title>
</head>
<body>
  {% extends 'base.html' %}
  {% block content %}
  <div id="formbody">
    <div class="form">
      <div style="display: flex;">
        <img id="headerpic" src="https://media.istockphoto.com/vectors/female-teacher-with-books-and-chalkboard-concept-illustration-for-vector-id1171911961?k=20&m=1171911961&s=612x612&w=0&h=hkvQDT55FFeMiI7w-hjoUp_MkbDupxEaLEypzdLZ4qc=" width="20%" height="10%" alt="">
        <h1 style=" font-weight: bold; font-size: 45px;color: purple;">User Management</h1>
      </div>
      <p style="color: purple; font-size: 19px;"> Fill in the form to register:</p> <hr>
   
    <form method="POST" enctype="multipart/form-data"  >
      {{ form.as_p }}
      {% csrf_token %}
        <button type="submit" 
        style="background-color: purple; 
        color: white;
        width: 98%;
        height: 40px;
         border-radius: 10px; 
         font-family: 'Montserrat', sans-serif;
         font-size: 20px;
         font-weight: bold;">
         SUBMIT</button>
    </form>
   
     
   
</div>
</div>
      <style>
       
          #formbody{
           
         display: flex;
         width: 75%;
         background-color: white;
         border-radius:20px ;
        margin-left: 11%; 
       } 
       
        
        .pic{
          width: 40%;
          margin-bottom: -2%;
        }
        
           body{
       
        font-weight: bold;
        font-family: 'Montserrat', sans-serif;
        font-size:15px;
      
        background-repeat: no-repeat;
          }
          h1{
          font-family: 'Montserrat', sans-serif;
          margin-top: 4%;
          }
          .form{
            margin:4% auto 0 auto;
            padding:30px;
            width:800px;
            height:auto;
            overflow:hidden;
           
            border-radius:20px; 
          }
          .form_control{
           width: 98%;
           outline: none;
           border: 2px solid rgb(99, 51, 99) ;
           font-size: 13px;
           padding: 8px 10px;
           border-radius: 5px;  
           font-family: 'Montserrat', sans-serif;
           font-weight: bold; 
           display: flex;  
       }
       #gender{
         background-color: white;
         width: 98%;
         height: auto;
       }
     
      </style>
    {% endblock content %}    
</body>
</html>

user/templates/user_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
   
    <title>Document</title>
</head>
<body style="background-color: rgb(211, 209, 209);" >

{% extends 'base.html' %}
{% block content %}
 <div id="formbody">
<div><h1 style=" padding: 20px; font-size: 30px;color:purple;margin-top: 3%;margin-left: 1%;font-family: 'Montserrat', sans-serif;">CODEHIVE 2021 TRAINERS.</h1>
<img id="headerpic" src="https://media.istockphoto.com/vectors/female-teacher-with-books-and-chalkboard-concept-illustration-for-vector-id1171911961?k=20&m=1171911961&s=612x612&w=0&h=hkvQDT55FFeMiI7w-hjoUp_MkbDupxEaLEypzdLZ4qc=" width="100%" alt=""></div>
    <table class="table table-striped" id="table">
        <tr style="color: rgb(94, 4, 94);font-size: 19px;font-weight: lighter;">
            <th>PROFILE</th>
            <th>FIRST NAME</th>
            <th>LAST NAME</th>
            <th>COURSE_NAME</th>
            <th>EDIT</th>
            <th>PROFILE</th>
            <th>DELETE</th>
                
        </tr>

    {% for user in page_obj %}
        <tr>
            <td><img id="img" src="{{ user.image.url }}" width="40px" height="40px" /></td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.course_name }}</td>
            <td><a id="href" href="{%url 'user:edit_user' id=user.id%}">Edit</a> </td>
            <td><a id="href"  href="{%url 'user:user_profile' id=user.id%}">Profile</a> </td>
            <td><a id="href"  href="{%url 'user:delete_user' id=user.id%}">Delete</a></td>
        </tr>
   
    {% endfor %}
    
    
</table>
<span class="step-links">
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</span>

   
        
   

</div>

<style>
    #headerpic{
        margin-bottom: 1%;
    }
     #formbody{
         display: flex;
         width: 95%;
         background-color: white;
         border-radius:20px ;
        margin-left: 2.5%; 
       }
    #table{
        margin-top: 3%;
        margin-left: 5%;
        margin-right: 1%;
        width: 100%;
        color: purple;
       
        
    }
    #img{
        border-radius: 40%;
    }
 
    #href{
        color: rgb(36, 28, 151);
    }
</style>


{% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    

</body>
</html>

user/templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <title>User Registration</title>
</head>
<body style="background-color: rgb(211, 209, 209)">
  {% extends 'base.html' %}
  {% block content %}
  <div id="formbody" >

  <div id="imgname">
  <img id="courses" src="{{ trainer.image.url }}" width="270px" height="320px" >
  <h1 style="font-size: 40px;color: rgb(77, 73, 77);;"><span style="font-size: larger; color: purple;"></span>{{trainer.first_name}} {{trainer.last_name}}</h1>
  <hr>
  
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><img id="phone" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfdhIprO1Kd3PlwoqSMZmeAMnF1iV1Y0R9SQ&usqp=CAU" width="20px" height="20px"><span style=" color: purple;">Email:</span>{{trainer.email}}</p>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><img id="phone" src="https://parlourhairlounge.ca/wp-content/uploads/2016/07/purple-phone-icon-md.png"  width="20px" height="20px"><span style="color: purple;">Phone Number:</span>0798676088</p>
 
  </div>

<div class="form" >
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">Gender:</span>{{trainer.gender}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">Company:</span>{{trainer.company}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">Joining Date:</span>{{trainer.joining_date}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">joining_date:</span>{{trainer.joining_date}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">Course Name:</span>{{trainer.course_name}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style=" color: purple;">City:</span>{{trainer.city}}</p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style="color: purple;">Resume:</span><a href="{{trainer.resume.url}}">Download</a></p><hr>
  <p style="font-size: 15px;color: rgb(77, 73, 77);;"><span style="color: purple;">Contract:</span><a href="{{trainer.contract.url}}">Download</a></p><hr>

  <a id="edit" href="{% url 'user:delete_user' user.id %}">Delete</a>
  <a id="edit" href="{% url 'user:edit_user' user.id %}">Edit</a>
 


    
     
   
</div>  
</div>
      <style>
        #edit{
          padding: 10px;
          color: white;
          background-color: purple;
          border: solid 1px ;
          border-radius: 10px;
          float: right;
          text-decoration: none;
          font-size: 17px;
        }
          #phone{
              margin-top: -1%;
          }
          p{
            font-family: 'Montserrat', sans-serif;
            margin-left: 2%;
            padding: 2px;
           

          }
        #courses{
       
          margin-top: 2%;
          margin-left: 3%;
          border-radius: 20px;
        }
        .pic{
          height: 25%;
          margin-top: -7%;
          width: 35%;
        }
        #formbody{
          background-color: white;
          display: flex;
          width: 1000px;
          font-weight: bold;
          margin-left: 16%;
          border-radius: 3%;
          height: 45%;   
        }
        #imgname{
          margin-left: 3%;
          margin-top: 3%;
          width: 50%;
        }
        
          body{
        background:#fcfafb;
       
          }
          
          h1{
           margin-top: 4%;
          font-weight: bold;
          font-family: 'Montserrat', sans-serif;
         
          
          }
          .form{
            font-family: 'Montserrat', sans-serif;
            font-weight: bold;
            font-size: 15px;
            padding:30px;
            width:700px;
            height:auto;
            overflow:hidden;
            color: rgb(29, 2, 29);
            border-radius:20px;
         
           
          }
          input{
           width: 98%;
           outline: none;
           border: 1px solid rgb(121, 83, 121) ;
           font-size: 13px;
           padding: 7px 10px;
           border-radius: 5px;  
           font-family: 'Montserrat', sans-serif;
           font-weight: bold;
           display: flex;  
           
       }
       #des{
         height: 1%;
         width: 98%;
         font-weight: bold;
       }
      
       
      </style>
  {% endblock content %}
</body>
</html>